"use client";

import React from "react";
import { Typography, Card, Divider, Button, Space } from "antd";
import { FileProtectOutlined, HomeOutlined } from "@ant-design/icons";
import { useRouter } from "next/navigation";
import { useLocale } from "next-intl";

const { Title, Paragraph, Text } = Typography;

// ==========================================
// TERMS CONTENT (18 Languages)
// ==========================================
const TRANSLATIONS: any = {
  // 1. English
  en: {
    title: "Terms of Service",
    lastUpdated: "Last Updated: January 2026",
    intro: "Please read these terms carefully before using Subtitle Translator.",
    sections: [
      { heading: "1. Acceptance of Terms", content: "By accessing and using this website, you accept and agree to be bound by the terms and provision of this agreement." },
      { heading: "2. Description of Service", content: "Subtitle Translator provides an online tool for translating subtitle files. We do not claim ownership of the content you upload." },
      { heading: "3. Privacy", content: "We value your privacy. Files are processed locally in your browser when possible. API keys are stored locally on your device." },
      { heading: "4. Intellectual Property", content: "You retain all rights to the subtitle files you upload. The translated output belongs to you." },
      { heading: "5. Disclaimer", content: "The service is provided 'AS IS'. We do not guarantee the accuracy of translations generated by AI." }
    ],
    backBtn: "Back to Home"
  },

  // 2. Simplified Chinese
  zh: {
    title: "服务条款",
    lastUpdated: "最后更新：2026年1月",
    intro: "使用字幕翻译器前请仔细阅读这些条款。",
    sections: [
      { heading: "1. 条款接受", content: "访问和使用本网站即表示您接受并同意受本协议条款的约束。" },
      { heading: "2. 服务说明", content: "字幕翻译器提供在线字幕翻译工具。我们不拥有您上传的内容。" },
      { heading: "3. 隐私", content: "我们重视您的隐私。文件尽可能在浏览器本地处理。API密钥仅存储在您的设备上。" },
      { heading: "4. 知识产权", content: "您保留上传文件的所有权利。翻译结果归您所有。" },
      { heading: "5. 免责声明", content: "本服务按'原样'提供。我们不保证AI生成翻译的准确性。" }
    ],
    backBtn: "返回首页"
  },

  // 3. Spanish
  es: {
    title: "Términos de Servicio",
    lastUpdated: "Última actualización: Enero 2026",
    intro: "Lea estos términos detenidamente antes de usar el Traductor de Subtítulos.",
    sections: [
      { heading: "1. Aceptación", content: "Al usar este sitio, acepta estar sujeto a estos términos." },
      { heading: "2. Servicio", content: "Proporcionamos una herramienta para traducir subtítulos. No reclamamos la propiedad de su contenido." },
      { heading: "3. Privacidad", content: "Sus archivos se procesan localmente. Las claves API se guardan en su dispositivo." },
      { heading: "4. Propiedad Intelectual", content: "Usted conserva los derechos de sus archivos. La traducción le pertenece." },
      { heading: "5. Renuncia", content: "El servicio se proporciona 'TAL CUAL'. No garantizamos la exactitud de las traducciones." }
    ],
    backBtn: "Volver al Inicio"
  },

  // 4. Hindi
  hi: {
    title: "सेवा की शर्तें",
    lastUpdated: "अंतिम अपडेट: जनवरी 2026",
    intro: "सबटाइटल ट्रांसलेटर का उपयोग करने से पहले कृपया इन शर्तों को ध्यान से पढ़ें।",
    sections: [
      { heading: "1. शर्तों की स्वीकृति", content: "इस वेबसाइट का उपयोग करके, आप इस समझौते की शर्तों से बाध्य होने के लिए सहमत हैं।" },
      { heading: "2. सेवा का विवरण", content: "हम सबटाइटल अनुवाद के लिए एक ऑनलाइन टूल प्रदान करते हैं। हम आपके द्वारा अपलोड की गई सामग्री के स्वामित्व का दावा नहीं करते हैं।" },
      { heading: "3. गोपनीयता", content: "हम आपकी गोपनीयता को महत्व देते हैं। फाइलें आपके ब्राउज़र में स्थानीय रूप से प्रोसेस की जाती हैं।" },
      { heading: "4. बौद्धिक संपदा", content: "आप अपनी अपलोड की गई फाइलों के सभी अधिकार रखते हैं।" },
      { heading: "5. अस्वीकरण", content: "सेवा 'जैसी है' वैसी ही प्रदान की जाती है। हम अनुवाद की सटीकता की गारंटी नहीं देते हैं।" }
    ],
    backBtn: "होम पर वापस जाएं"
  },

  // 5. Arabic
  ar: {
    title: "شروط الخدمة",
    lastUpdated: "آخر تحديث: يناير 2026",
    intro: "يرجى قراءة هذه الشروط بعناية قبل استخدام مترجم الترجمة.",
    sections: [
      { heading: "1. قبول الشروط", content: "من خلال الوصول إلى هذا الموقع، فإنك توافق على الالتزام بشروط هذه الاتفاقية." },
      { heading: "2. وصف الخدمة", content: "نحن نقدم أداة لترجمة ملفات الترجمة. نحن لا نطالب بملكية المحتوى الذي تقوم بتحميله." },
      { heading: "3. الخصوصية", content: "تتم معالجة الملفات محلياً في متصفحك. يتم تخزين مفاتيح API على جهازك." },
      { heading: "4. الملكية الفكرية", content: "أنت تحتفظ بجميع الحقوق لملفاتك. الترجمة الناتجة ملك لك." },
      { heading: "5. إخلاء المسؤولية", content: "يتم تقديم الخدمة 'كما هي'. نحن لا نضمن دقة الترجمات." }
    ],
    backBtn: "العودة للرئيسية"
  },

  // 6. Portuguese
  pt: {
    title: "Termos de Serviço",
    lastUpdated: "Última atualização: Janeiro 2026",
    intro: "Leia estes termos cuidadosamente antes de usar o Tradutor de Legendas.",
    sections: [
      { heading: "1. Aceitação", content: "Ao usar este site, você concorda com estes termos." },
      { heading: "2. Serviço", content: "Fornecemos uma ferramenta para traduzir legendas. Não reivindicamos a propriedade do seu conteúdo." },
      { heading: "3. Privacidade", content: "Seus arquivos são processados localmente. As chaves de API ficam no seu dispositivo." },
      { heading: "4. Propriedade Intelectual", content: "Você mantém os direitos dos seus arquivos. A tradução pertence a você." },
      { heading: "5. Isenção", content: "O serviço é fornecido 'COMO ESTÁ'. Não garantimos a precisão das traduções." }
    ],
    backBtn: "Voltar ao Início"
  },

  // 7. French
  fr: {
    title: "Conditions d'utilisation",
    lastUpdated: "Dernière mise à jour : Janvier 2026",
    intro: "Veuillez lire attentivement ces conditions avant d'utiliser le service.",
    sections: [
      { heading: "1. Acceptation", content: "En utilisant ce site, vous acceptez d'être lié par ces conditions." },
      { heading: "2. Service", content: "Nous fournissons un outil de traduction de sous-titres. Nous ne revendiquons pas la propriété de votre contenu." },
      { heading: "3. Confidentialité", content: "Les fichiers sont traités localement. Les clés API sont stockées sur votre appareil." },
      { heading: "4. Propriété intellectuelle", content: "Vous conservez tous les droits sur vos fichiers." },
      { heading: "5. Avertissement", content: "Le service est fourni 'TEL QUEL'. Nous ne garantissons pas l'exactitude des traductions." }
    ],
    backBtn: "Retour à l'accueil"
  },

  // 8. German
  de: {
    title: "Nutzungsbedingungen",
    lastUpdated: "Letzte Aktualisierung: Januar 2026",
    intro: "Bitte lesen Sie diese Bedingungen sorgfältig durch.",
    sections: [
      { heading: "1. Annahme", content: "Durch die Nutzung dieser Website stimmen Sie diesen Bedingungen zu." },
      { heading: "2. Dienstleistung", content: "Wir bieten ein Tool zur Untertitelübersetzung. Wir beanspruchen kein Eigentum an Ihren Inhalten." },
      { heading: "3. Datenschutz", content: "Dateien werden lokal verarbeitet. API-Schlüssel werden auf Ihrem Gerät gespeichert." },
      { heading: "4. Geistiges Eigentum", content: "Sie behalten alle Rechte an Ihren Dateien." },
      { heading: "5. Haftungsausschluss", content: "Der Dienst wird 'WIE BESEHEN' bereitgestellt. Keine Garantie für Übersetzungsgenauigkeit." }
    ],
    backBtn: "Zurück zur Startseite"
  },

  // 9. Japanese
  ja: {
    title: "利用規約",
    lastUpdated: "最終更新日：2026年1月",
    intro: "本サービスを利用する前に、これらの条件をよくお読みください。",
    sections: [
      { heading: "1. 同意", content: "本サイトを利用することで、本規約に同意したものとみなされます。" },
      { heading: "2. サービス内容", content: "字幕翻訳ツールを提供します。アップロードされたコンテンツの所有権は主張しません。" },
      { heading: "3. プライバシー", content: "ファイルはブラウザ内でローカルに処理されます。APIキーはデバイスに保存されます。" },
      { heading: "4. 知的財産権", content: "アップロードしたファイルの権利は利用者に帰属します。" },
      { heading: "5. 免責事項", content: "サービスは「現状有姿」で提供されます。翻訳の正確性を保証するものではありません。" }
    ],
    backBtn: "ホームに戻る"
  },

  // 10. Korean
  ko: {
    title: "서비스 약관",
    lastUpdated: "마지막 업데이트: 2026년 1월",
    intro: "서비스를 사용하기 전에 이 약관을 주의 깊게 읽어주세요.",
    sections: [
      { heading: "1. 약관 동의", content: "이 사이트를 사용함으로써 귀하는 이 약관에 동의하게 됩니다." },
      { heading: "2. 서비스 설명", content: "자막 번역 도구를 제공합니다. 당사는 귀하의 콘텐츠에 대한 소유권을 주장하지 않습니다." },
      { heading: "3. 개인정보 보호", content: "파일은 브라우저에서 로컬로 처리됩니다. API 키는 기기에 저장됩니다." },
      { heading: "4. 지적 재산권", content: "업로드한 파일에 대한 모든 권리는 귀하에게 있습니다." },
      { heading: "5. 면책 조항", content: "서비스는 '있는 그대로' 제공됩니다. 번역의 정확성을 보장하지 않습니다." }
    ],
    backBtn: "홈으로 돌아가기"
  },

  // 11. Russian
  ru: {
    title: "Условия использования",
    lastUpdated: "Последнее обновление: Январь 2026",
    intro: "Пожалуйста, внимательно ознакомьтесь с этими условиями.",
    sections: [
      { heading: "1. Принятие условий", content: "Используя этот сайт, вы соглашаетесь с данными условиями." },
      { heading: "2. Описание услуги", content: "Мы предоставляем инструмент для перевода субтитров. Мы не претендуем на авторские права вашего контента." },
      { heading: "3. Конфиденциальность", content: "Файлы обрабатываются локально. API-ключи хранятся на вашем устройстве." },
      { heading: "4. Интеллектуальная собственность", content: "Вы сохраняете все права на свои файлы." },
      { heading: "5. Отказ от ответственности", content: "Сервис предоставляется 'КАК ЕСТЬ'. Мы не гарантируем точность перевода." }
    ],
    backBtn: "На главную"
  },

  // 12. Vietnamese
  vi: {
    title: "Điều khoản dịch vụ",
    lastUpdated: "Cập nhật lần cuối: Tháng 1 năm 2026",
    intro: "Vui lòng đọc kỹ các điều khoản này trước khi sử dụng.",
    sections: [
      { heading: "1. Chấp nhận điều khoản", content: "Bằng cách sử dụng trang web này, bạn đồng ý với các điều khoản này." },
      { heading: "2. Mô tả dịch vụ", content: "Chúng tôi cung cấp công cụ dịch phụ đề. Chúng tôi không yêu cầu quyền sở hữu nội dung của bạn." },
      { heading: "3. Quyền riêng tư", content: "Tệp được xử lý cục bộ trên trình duyệt. Khóa API được lưu trên thiết bị của bạn." },
      { heading: "4. Sở hữu trí tuệ", content: "Bạn giữ mọi quyền đối với các tệp của mình." },
      { heading: "5. Tuyên bố từ chối trách nhiệm", content: "Dịch vụ được cung cấp 'NGUYÊN TRẠNG'. Chúng tôi không đảm bảo độ chính xác của bản dịch." }
    ],
    backBtn: "Trở về trang chủ"
  },

  // 13. Thai
  th: {
    title: "เงื่อนไขการให้บริการ",
    lastUpdated: "อัปเดตล่าสุด: มกราคม 2026",
    intro: "โปรดอ่านเงื่อนไขเหล่านี้อย่างละเอียดก่อนใช้งาน",
    sections: [
      { heading: "1. การยอมรับเงื่อนไข", content: "การใช้เว็บไซต์นี้ถือว่าคุณยอมรับเงื่อนไขเหล่านี้" },
      { heading: "2. รายละเอียดบริการ", content: "เราให้บริการเครื่องมือแปลคำบรรยาย เราไม่อ้างสิทธิ์ความเป็นเจ้าของในเนื้อหาของคุณ" },
      { heading: "3. ความเป็นส่วนตัว", content: "ไฟล์จะถูกประมวลผลในเบราว์เซอร์ของคุณ คีย์ API จะถูกเก็บไว้ในอุปกรณ์ของคุณ" },
      { heading: "4. ทรัพย์สินทางปัญญา", content: "คุณยังคงสิทธิ์ทั้งหมดในไฟล์ของคุณ" },
      { heading: "5. ข้อปฏิเสธความรับผิด", content: "บริการนี้ให้บริการ 'ตามสภาพ' เราไม่รับประกันความถูกต้องของการแปล" }
    ],
    backBtn: "กลับสู่หน้าหลัก"
  },

  // 14. Turkish
  tr: {
    title: "Hizmet Şartları",
    lastUpdated: "Son Güncelleme: Ocak 2026",
    intro: "Lütfen kullanmadan önce bu şartları dikkatlice okuyun.",
    sections: [
      { heading: "1. Kabul", content: "Bu siteyi kullanarak bu şartları kabul etmiş sayılırsınız." },
      { heading: "2. Hizmet", content: "Altyazı çeviri aracı sunuyoruz. İçeriğiniz üzerinde hak iddia etmiyoruz." },
      { heading: "3. Gizlilik", content: "Dosyalar yerel olarak işlenir. API anahtarları cihazınızda saklanır." },
      { heading: "4. Fikri Mülkiyet", content: "Dosyalarınızın tüm hakları size aittir." },
      { heading: "5. Yasal Uyarı", content: "Hizmet 'OLDUĞU GİBİ' sunulur. Çeviri doğruluğunu garanti etmiyoruz." }
    ],
    backBtn: "Ana Sayfaya Dön"
  },

  // 15. Traditional Chinese
  "zh-hant": {
    title: "服務條款",
    lastUpdated: "最後更新：2026年1月",
    intro: "使用本服務前請仔細閱讀這些條款。",
    sections: [
      { heading: "1. 接受條款", content: "使用本網站即表示您同意受本協議約束。" },
      { heading: "2. 服務說明", content: "我們提供字幕翻譯工具。我們不擁有您上傳的內容。" },
      { heading: "3. 隱私", content: "檔案在瀏覽器本地處理。API 金鑰僅存儲在您的裝置上。" },
      { heading: "4. 智慧財產權", content: "您保留檔案的所有權利。翻譯結果歸您所有。" },
      { heading: "5. 免責聲明", content: "本服務按「原樣」提供。我們不保證翻譯的準確性。" }
    ],
    backBtn: "返回首頁"
  },

  // 16. Bengali
  bn: {
    title: "পরিষেবার শর্তাবলী",
    lastUpdated: "সর্বশেষ আপডেট: জানুয়ারী 2026",
    intro: "ব্যবহার করার আগে দয়া করে এই শর্তাবলী সাবধানে পড়ুন।",
    sections: [
      { heading: "1. শর্তাবলী গ্রহণ", content: "এই সাইট ব্যবহার করে, আপনি এই শর্তাবলীতে সম্মত হন।" },
      { heading: "2. পরিষেবা", content: "আমরা সাবটাইটেল অনুবাদের টুল প্রদান করি। আপনার কন্টেন্টের মালিকানা আমরা দাবি করি না।" },
      { heading: "3. গোপনীয়তা", content: "ফাইলগুলি স্থানীয়ভাবে প্রসেস হয়। API কী আপনার ডিভাইসে সংরক্ষিত থাকে।" },
      { heading: "4. মেধাসম্পদ", content: "আপনার ফাইলের সব অধিকার আপনার।" },
      { heading: "5. দাবিত্যাগ", content: "পরিষেবাটি 'যেমন আছে' ভিত্তিতে প্রদান করা হয়। অনুবাদের নির্ভুলতার গ্যারান্টি আমরা দিই না।" }
    ],
    backBtn: "হোমে ফিরে যান"
  },

  // 17. Indonesian
  id: {
    title: "Syarat Layanan",
    lastUpdated: "Terakhir Diperbarui: Januari 2026",
    intro: "Harap baca syarat ini dengan cermat sebelum menggunakan.",
    sections: [
      { heading: "1. Penerimaan", content: "Dengan menggunakan situs ini, Anda menyetujui syarat ini." },
      { heading: "2. Layanan", content: "Kami menyediakan alat penerjemah subtitle. Kami tidak mengklaim kepemilikan konten Anda." },
      { heading: "3. Privasi", content: "File diproses secara lokal. Kunci API disimpan di perangkat Anda." },
      { heading: "4. Kekayaan Intelektual", content: "Anda memegang semua hak atas file Anda." },
      { heading: "5. Penafian", content: "Layanan disediakan 'APA ADANYA'. Kami tidak menjamin keakuratan terjemahan." }
    ],
    backBtn: "Kembali ke Beranda"
  },

  // 18. Italian
  it: {
    title: "Termini di Servizio",
    lastUpdated: "Ultimo aggiornamento: Gennaio 2026",
    intro: "Si prega di leggere attentamente questi termini.",
    sections: [
      { heading: "1. Accettazione", content: "Utilizzando questo sito, accetti questi termini." },
      { heading: "2. Servizio", content: "Forniamo uno strumento per tradurre sottotitoli. Non rivendichiamo la proprietà dei tuoi contenuti." },
      { heading: "3. Privacy", content: "I file vengono elaborati localmente. Le chiavi API sono salvate sul tuo dispositivo." },
      { heading: "4. Proprietà intellettuale", content: "Mantieni tutti i diritti sui tuoi file." },
      { heading: "5. Disclaimer", content: "Il servizio è fornito 'COSÌ COM'È'. Non garantiamo l'accuratezza delle traduzioni." }
    ],
    backBtn: "Torna alla Home"
  }
};

export default function TermsClient() {
  const router = useRouter();
  const locale = useLocale();

  // Fallback to English if language is missing
  const t = TRANSLATIONS[locale] || TRANSLATIONS['en'];

  return (
    <div className="terms-container" style={{ maxWidth: 800, margin: "0 auto", padding: "40px 20px" }}>
      
      <div style={{ textAlign: "center", marginBottom: 40 }}>
        <Title level={1}>
          <FileProtectOutlined style={{ marginRight: 12, color: "#1890ff" }} />
          {t.title}
        </Title>
        <Text type="secondary">{t.lastUpdated}</Text>
      </div>

      <Card style={{ boxShadow: "0 2px 8px rgba(0,0,0,0.05)" }}>
        <Paragraph style={{ fontSize: 16, marginBottom: 32 }}>
          {t.intro}
        </Paragraph>

        <Space direction="vertical" size={32} style={{ width: "100%" }}>
          {t.sections.map((section: any, index: number) => (
            <div key={index}>
              <Title level={4}>{section.heading}</Title>
              <Paragraph style={{ color: "rgba(0, 0, 0, 0.65)" }}>
                {section.content}
              </Paragraph>
            </div>
          ))}
        </Space>

        <Divider />

        <div style={{ textAlign: "center", marginTop: 32 }}>
          <Button 
            type="primary" 
            size="large" 
            icon={<HomeOutlined />} 
            onClick={() => router.push(`/${locale}`)}
          >
            {t.backBtn}
          </Button>
        </div>
      </Card>

      <div style={{ textAlign: "center", marginTop: 40, opacity: 0.5 }}>
        <Text type="secondary" style={{ fontSize: 12 }}>
          © 2026 Subtitle Translator. All rights reserved.
        </Text>
      </div>
    </div>
  );
}
